//Auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const AUTH_ATTEMPT = 'AUTH_ATTEMPT';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const SIGN_IN_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SIGN_IN_USER_FAIL = 'SIGN_IN_USER_FAIL';

// Add Show Details
export const COUNTRY_CHANGED = 'COUNTRY_CHANGED';
export const DATE_CHANGED = 'DATE_CHANGED';
export const CITY_CHANGED = 'CITY_CHANGED';
export const SET_START_TIME_CHANGED = 'SET_START_TIME_CHANGED';
export const SET_END_TIME_CHANGED = 'SET_END_TIME_CHANGED';
export const FEE_CHANGED = 'FEE_CHANGED';
